#include <stdio.h>
#include "minunit.h"
#include "../minty_util.h"
#include "../lexer.h"
#include "../parser.h"
#include "../AST.h"

int tests_run = 0;

char *test_tiny_prog_same() {

	LinkedList *prog_tokens = lex("fn main() {return 0;}");

	Program *parsed_prog = parse_program(prog_tokens);

	// AST representing the AST that should be generated by the call to
	// parse_program above
	LinkedList *stmts = LinkedList_init();
	LinkedList_append(stmts, Return_init(IntegerLiteral_init(0)));
	LinkedList *fns = LinkedList_init();
	LinkedList_append(fns, FNDecl_init(safe_strdup("main"),
		LinkedList_init(), stmts));
	Program *ast = Program_init(fns);

	// Assert that the two ASTs are the same
	mu_assert(Program_equals(parsed_prog, ast), "test_tiny_prog_same failed!");

	// Free things
	int i;
	for(i = 0; i < LinkedList_length(prog_tokens); i++)
		Token_free(LinkedList_get(prog_tokens, i));
	Program_free(parsed_prog);
	Program_free(ast);

	return NULL;
}

char *test_tiny_prog_diff() {

	LinkedList *prog_tokens = lex("fn main() {return 0;}");

	Program *parsed_prog = parse_program(prog_tokens);

	// AST that should NOT return true when compared to the above AST
	LinkedList *stmts = LinkedList_init();
	LinkedList_append(stmts, Print_init(Identifier_init(safe_strdup("hello"))));
	LinkedList *fns = LinkedList_init();
	LinkedList_append(fns, FNDecl_init(safe_strdup("main"),
		LinkedList_init(), stmts));
	Program *ast = Program_init(fns);

	// Assert that the two ASTs are the same
	mu_assert(!Program_equals(parsed_prog, ast), "test_tiny_prog_diff failed!");

	// Free things
	int i;
	for(i = 0; i < LinkedList_length(prog_tokens); i++)
		Token_free(LinkedList_get(prog_tokens, i));
	Program_free(parsed_prog);
	Program_free(ast);

	return NULL;
}

char *test_two_functions() {

	LinkedList *prog_tokens = lex(" \
		fn main() { \
			return binary_add(4, 5); \
		} \
		fn binary_add(num1, num2) { \
			return num1 + num2; \
		}");

	Program *parsed_prog = parse_program(prog_tokens);

	// main function
	LinkedList *caller_args = LinkedList_init();
	LinkedList_append(caller_args, IntegerLiteral_init(4));
	LinkedList_append(caller_args, IntegerLiteral_init(5));
	LinkedList *main_stmts = LinkedList_init();
	LinkedList_append(main_stmts, Return_init(
		FNCall_init(safe_strdup("binary_add"), caller_args)));
	FNDecl *main_fn = FNDecl_init(
		safe_strdup("main"),
		LinkedList_init(),
		main_stmts);

	// binary_add function
	LinkedList *callee_args = LinkedList_init();
	LinkedList_append(callee_args, safe_strdup("num1"));
	LinkedList_append(callee_args, safe_strdup("num2"));
	LinkedList *binary_add_stmts = LinkedList_init();
	LinkedList_append(binary_add_stmts, Return_init(
		ArithmeticExpr_init(
			Identifier_init(safe_strdup("num1")),
			safe_strdup("+"),
			Identifier_init(safe_strdup("num2")))));
	FNDecl *binary_add_fn = FNDecl_init(
		safe_strdup("binary_add"),
		callee_args,
		binary_add_stmts);

	// Program object
	LinkedList *fns = LinkedList_init();
	LinkedList_append(fns, main_fn);
	LinkedList_append(fns, binary_add_fn);
	Program *ast = Program_init(fns);

	mu_assert(Program_equals(parsed_prog, ast), "test_two_functions failed!");

	return NULL;
}

char *all_tests() {

	mu_suite_start();
	
	mu_run_test(test_tiny_prog_same);
	mu_run_test(test_tiny_prog_diff);
	mu_run_test(test_two_functions);

	return NULL;
}

RUN_TESTS(all_tests);