# Sets the command line flags used to -Wall (show all warnings for 'normal' programs) and -g (produce debugging info)
CFLAGS=-Wall -g

# Adding this line means you can just run 'make' and ex1 will be built
all: lexer AST minty_util

# Command that is run when 'make clean' is run
clean:
	rm -f lexer.o AST.o minty_util.o